[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "price-tracker"
readme = "README.md"
version = "V0.1.0"

license = { file = "LICENSE" }
authors = [
    { name = "Sanjay Patel" }
]

[tool.setuptools]
package-dir = {"" = "src"}

[project-urls]
Homepage = "https://github.com/XSanjayPatelX/Price-Tracker"